### ISSUE TITLE
shortest path finding in real time. 

### ISSUE THREAD

**Issue by RiyaUplenchwar** [markosski/shortestPath#1]
The way you had done dijkstra's, in that you had entered the data manually. If we want to do it directly using the google maps API, how can we do that. I am trying to do that by using A* algorithm, but getting stuck in taking the data directly from google maps. Do help me with this thing....Thank you.

**Comment by markosski** [comment]
I'm sure google doesn't provide ability to directly download their road network data. You may have more luck with OpenStreetMap. Maybe this thread will be helpful:
http://gis.stackexchange.com/questions/44676/where-can-i-download-the-google-road-network-as-shapefile
